# list with combinations of complete words to search in the text
list_words_set_railway = [
    ("train", "fire"),
    ("train", "collision"),
    ("train", "derail"),
    ("train", "derailment"),
    ("train", "collided"),
    ("train", "explosion"),
    ("train", "sabotage"),
    ("train", "attack"),
    ("train", "arson"),
    ("train", "destroy"),
    ("train", "damage"),
    ("train", "diversion"),
    ("train", "blow"),
    ("train", "hit"),
    ("train", "struck"),
    ("train", "injured"),
    ("train", "accident"),
    ("train", "accidents"),
    #
    ("trains", "fire"),
    ("trains", "collision"),
    ("trains", "derail"),
    ("trains", "derailment"),
    ("trains", "collided"),
    ("trains", "explosion"),
    ("trains", "sabotage"),
    ("trains", "attack"),
    ("trains", "arson"),
    ("trains", "destroy"),
    ("trains", "damage"),
    ("trains", "diversion"),
    ("trains", "blow"),
    ("trains", "hit"),
    ("trains", "struck"),
    ("trains", "accident"),
    ("trains", "accidents"),
    ("trains", "injured"),
    ("freight", "train"),
    ("passenger", "train"),
    ("cargo", "train"),
    ("fuel", "train"),
    ("locomotive", "burned"),
    ("locomotives", "burned"),
    ("tank", "derailed"),
    ("tanks", "derailed"),
    ("railcars", "fire"),
    ("railcars", "derailed"),
    ("wagons", "fire"),
    ("wagons", "burned"),
    ("wagons", "exploded"),
    ("tracks", "blown"),
    ("tracks", "damaged"),
    ("bridge", "railway"),
    ("bridge", "railroad"),
]

# list with combinations of substrings to search in the text
list_substr_set_railway = [
    ("sabotage", "railway"),
    ("sabotage", "railroad"),
    ("sabotage", "station"),
    ("sabotage", "rail"),
    ("sabotage", "freight"),
    ("sabotage", "relay"),
    ("sabotage", "accumulator"),
    ("sabotage", "electric"),
    ("sabotage", "battery"),
    #
    ("relay", "box"),
    ("relay", "room"),
    ("relay", "cabins"),
    ("relay", "cabinet"),
    #
    ("cabinet", "accumulator"),
    ("cabinet", "electric"),
    ("cabinet", "electrical"),
    ("cabinet", "battery"),
    #
    ("railway", "bombing"),
    ("railway", "blow"),
    ("railway", "explosion"),
    ("railway", "damage"),
    ("railway", "accident"),
    #
    ("railroad", "bombing"),
    ("railroad", "blow"),
    ("railroad", "explosion"),
    ("railroad", "damage"),
    ("railroad", "accident"),
    #
    ("arson", "relay"),
    ("arson", "railway"),
    ("arson", "cabinet"),
    ("arson", "substation"),
    ("arson", "freight"),
    ("arson", "locomotive"),
    #
    ("fire", "relay"),
    ("fire", "cabinet"),
    ("fire", "substation"),
    #
    ("diversion", "railway"),
    ("diversion", "railroad"),
    #
    ("damage", "railway"),
    ("damage", "railroad"),
    #
    ("collision", "freight"),
    #
    ("wagons", "derail"),
    ("car", "derail"),
    #
    ("locomotive", "fire"),
    ("locomotive", "explosion"),
    ("locomotive", "collision"),
    ("locomotive", "derail"),
    ("locomotive", "damage"),
    ("locomotive", "sabotage"),
    ("locomotive", "destroy"),
    ("locomotive", "attack"),
    ("locomotive", "accident"),
    ("locomotive", "hit"),
    ("locomotive", "struck"),
    #
    ("rail", "fire"),
    ("rail", "explosion"),
    ("rail", "collision"),
    ("rail", "derail"),
    ("rail", "damage"),
    ("rail", "sabotage"),
    ("rail", "accident"),
    ("rail", "hit"),
    ("rail", "struck"),
    #
    ("freight", "fire"),
    ("freight", "explosion"),
    ("freight", "collision"),
    ("freight", "derail"),
    ("freight", "damage"),
    ("freight", "sabotage"),
    ("freight", "accident"),
    ("freight", "hit"),
    ("freight", "struck"),
    ("freight", "injured"),
    #
    ("destroy", "railway"),
    ("destroy", "railroad"),
    ("destroy", "relay"),
    ("destroy", "cabinet"),
    ("destroy", "substation"),
    #
    ("attack", "railway"),
    ("attack", "railroad"),
    ("attack", "relay"),
    ("attack", "cabinet"),
    ("attack", "substation"),
    #
    ("track", "damage"),
    ("track", "sabotage"),
    ("track", "fire"),
    ("track", "explosion"),
    ("track", "collision"),
    ("track", "derail"),
    ("track", "destroy"),
    ("track", "attack"),
    #
    ("carriage", "fire"),
    ("carriage", "explosion"),
    ("carriage", "collision"),
    ("carriage", "derail"),
    ("carriage", "damage"),
    ("carriage", "sabotage"),
    ("carriage", "destroy"),
    ("carriage", "attack"),
    #
    ("crossing", "hit"),
    ("crossing", "struck"),
    ("crossing", "injured"),
    # sabotage / incendie criminel sur l'infrastructure
    ("sabotage", "signal"),
    ("sabotage", "traction"),
    ("sabotage", "locomotive"),
    ("sabotage", "track"),
    ("sabotage", "wagon"),
    ("sabotage", "substation"),
    ("sabotage", "interlocking"),
    ("arson", "signal"),
    ("arson", "traction"),
    ("arson", "interlocking"),
    ("arson", "track"),
    ("arson", "wagon"),
    ("arson", "depot"),
    #
    # signalisation / enclenchement
    ("signal", "fire"),
    ("signal", "arson"),
    ("signal", "damage"),
    ("signal", "destroy"),
    ("signalling", "fire"),
    ("signaling", "fire"),
    ("interlocking", "fire"),
    ("interlocking", "damage"),
    ("interlocking", "destroy"),
    ("switch", "arson"),
    ("switch", "sabotage"),
    #
    # alimentation / traction
    ("traction", "fire"),
    ("traction", "explosion"),
    ("traction", "damage"),
    ("traction", "destroy"),
    ("traction", "attack"),
    ("catenary", "damage"),
    ("catenary", "explosion"),
    ("catenary", "fire"),
    ("catenary", "sabotage"),
    ("overhead", "railway"),
    ("contact", "network"),
    ("substation", "explosion"),
    ("substation", "damage"),
    ("substation", "sabotage"),
    ("cable", "railway"),
    ("cable", "cut"),
    #
    # railway / railroad avec événements supplémentaires
    ("railway", "fire"),
    ("railway", "burn"),
    ("railway", "derail"),
    ("railway", "crash"),
    ("railway", "attack"),
    ("railway", "sabotage"),
    ("railway", "drone"),
    ("railway", "shelling"),
    ("railway", "strike"),
    ("railway", "mine"),
    ("railway", "blast"),
    ("railway", "incident"),
    ("railway", "bridge"),
    ("railway", "destroy"),
    ("railroad", "fire"),
    ("railroad", "burn"),
    ("railroad", "derail"),
    ("railroad", "crash"),
    ("railroad", "sabotage"),
    ("railroad", "drone"),
    ("railroad", "shelling"),
    ("railroad", "strike"),
    ("railroad", "mine"),
    ("railroad", "blast"),
    ("railroad", "incident"),
    #
    # rail
    ("rail", "bomb"),
    ("rail", "blast"),
    ("rail", "blown"),
    ("rail", "burn"),
    ("rail", "explosive"),
    #
    # ponts
    ("bridge", "blow"),
    ("bridge", "explosion"),
    ("bridge", "damage"),
    ("bridge", "sabotage"),
    ("bridge", "railway"),
    #
    # gares / dépôts
    ("station", "fire"),
    ("station", "explosion"),
    ("station", "attack"),
    ("station", "strike"),
    ("station", "shelling"),
    ("depot", "fire"),
    ("depot", "explosion"),
    ("depot", "attack"),
    ("depot", "strike"),
    ("depot", "sabotage"),
    #
    # wagons / citernes
    ("wagon", "fire"),
    ("wagon", "explosion"),
    ("wagon", "derail"),
    ("wagons", "fire"),
    ("wagons", "collision"),
    ("wagons", "explosion"),
    ("tank", "derail"),
    ("tanker", "fire"),
    ("tanker", "explosion"),
    ("tanker", "derail"),
    ("railcar", "fire"),
    ("railcar", "derail"),
    #
    # locomotives
    ("locomotive", "burn"),
    ("locomotive", "blow"),
    ("locomotive", "drone"),
    ("locomotive", "mine"),
    #
    # fret
    ("freight", "burn"),
    ("freight", "blast"),
    ("freight", "fuel"),
    #
    # passages à niveau
    ("crossing", "collision"),
    ("crossing", "accident"),
    ("crossing", "crash"),
    ("crossing", "killed"),
]


# list with expressions to search in the text
list_expression_railways = [
    "relay box",
    "relay boxes",
    "relay room",
    "relay cabins",
    "relay cabinet",
    "relay cabinets",
    "accumulator cabinet",
    "accumulator cabinets",
    "electrical cabinet",
    "electrical cabinets",
    "electric cabinet",
    "electric cabinets",
    "railway bombing",
    "battery cabinet",
    "battery cabinets",
    "railway sabotage",
    "railway explosion",
    "railway track damage",
    "railway was blown up",
    "railway tracks damage",
    "railway diversion",
    "railway station",
    "railway blast",
    "wagons derailed",
    "wagons derailment",
    "train fire",
    "train sabotage",
    "train collision",
    "train collided",
    "train derailment",
    "train equipment fire",
    "arson attack",
    "arson on railway",
    "arson on railway",
    "arson on the railway",
    "arson of relay",
    "fire to railway",
    "fire to a cabinet",
    "fire to a cabinets",
    "fire to the cabinet",
    "fire to the cabinets",
    "fire to a substation",
    "fire at a railway",
    "sabotage on the railway",
    "sabotage on railway",
    "sabotage of railway",
    "sabotage at a railroad",
    "diversion on railway",
    "diversions on railway",
    "diversions on the railway",
    "diversion on the railroad",
    "diversions on the railroad",
    "damage to railway",
    "damage to railroad",
    "damaged railway",
    "damaged railroad",
    "damaging railway",
    "damaging railroad",
    "blowing up railway",
    "blowing up railroad",
    "blow up railway",
    "blow up railroad",
    "railroad was blown up",
    "cars derailed",
    "set fire to relay",
    "destroy railroad",
    "rail sabotage",
    "attacks on railroad",
    "attacked a traction",
    "attacked a railway",
    "attacked a railroad",
    "attacks on the railway",
    "explosion of railway",
    "SCB blocks",
    "SCB block",
    "train derailed",
    "train crash",
    "train crashed",
    "train accident",
    "train explosion",
    "train was blown up",
    "train was set on fire",
    "train caught fire",
    "train hit by",
    "hit by a train",
    "struck by a train",
    "hit by train",
    "run over by a train",
    "freight train",
    "freight train derailed",
    "freight train fire",
    "passenger train",
    "cargo train",
    "fuel train",
    "ammunition train",
    "tank cars",
    "tank wagons",
    "tank car fire",
    "wagons caught fire",
    "wagons were set on fire",
    "wagons burned",
    "railcars derailed",
    #
    # perturbation du trafic
    "train delays",
    "trains delayed",
    "trains were delayed",
    "delayed trains",
    "train traffic",
    "train movement",
    "train service",
    "railway traffic",
    "traffic was suspended",
    "traffic was halted",
    "traffic disruption",
    #
    # infrastructure
    "railway line",
    "railway lines",
    "railway tracks",
    "railway track",
    "railway bridge",
    "railway infrastructure",
    "railway substation",
    "railway depot",
    "locomotive depot",
    "tracks were blown up",
    "blew up tracks",
    "blew up the railway",
    "blown up railway",
    "blown up the railway",
    "blown up tracks",
    "mined railway",
    "railway was mined",
    "rail track blown",
    "rail track was damaged",
    "track was damaged",
    #
    # signalisation / alimentation
    "signal box",
    "signal boxes",
    "signalling equipment",
    "signaling equipment",
    "signalling cabinet",
    "signaling cabinet",
    "interlocking",
    "interlocking system",
    "traction substation",
    "traction substations",
    "traction power",
    "overhead line",
    "overhead lines",
    "overhead wire",
    "overhead wires",
    "contact network",
    "contact wire",
    "catenary",
    "SCB equipment",
    "signalling, centralization and blocking",
    "signaling, centralization and blocking",
    "automatic block",
    "automatic blocking",
    "relay cabinet fire",
    "relay cabinet arson",
    "relay cabinet was set on fire",
    "relay boxes were set on fire",
    "relay box fire",
    "relay room fire",
    #
    # incendie criminel
    "set fire to a locomotive",
    "set fire to the locomotive",
    "set fire to a relay",
    "set fire to a signal",
    "set fire to the railway",
    "set fire to the relay cabinet",
    "set fire to a railway",
    "set fire to a train",
    "burned a locomotive",
    "burned a relay",
    "burned railway",
    "burning a relay",
    "railway arson",
    "arson of a locomotive",
    "arson of a railway",
    "arson attack on railway",
    "arson attack on a railway",
    "torched a relay",
    "torched a locomotive",
    "torched railway",
    #
    # sabotage / attaque
    "railway sabotage attempt",
    "attempted sabotage",
    "sabotaged the railway",
    "sabotaged a railway",
    "sabotaged railway",
    "sabotaged a locomotive",
    "sabotage of a locomotive",
    "sabotage of a relay",
    "sabotage of signalling",
    "sabotage of signaling",
    "attack on railway",
    "attack on the railway",
    "attack on a railway",
    "attack on a train",
    "attack on trains",
    "attacked a train",
    "attacked trains",
    "drone attack on railway",
    "drone attack on a train",
    "drone strike on railway",
    "drone strike on a train",
    "strike on a railway",
    "strike on railway",
    "strike on a station",
    "shelling of railway",
    "shelling of a train",
    "railway was shelled",
    "improvised explosive device",
    "IED on the railway",
    "IED on railway",
    "explosive device on the railway",
    "explosive device under",
    #
    # acteurs / opérateurs
    "Russian Railways",
    # "RZD",
    "Belarusian Railways",
    "Belarusian railway",
    "Ukrzaliznytsia",
    "Ukrainian Railways",
    "railway partisans",
    "rail partisans",
    "railway workers",
    "railway troops",
    #
    # passages à niveau / accidents de personnes
    "level crossing",
    "level crossing accident",
    "railway crossing",
    "railway crossing accident",
    "crossing collision",
]

# List with individual words to search in the text
list_word_railways = [
    "167",
    "205",
    "205.5",
    # "205-205.5",
    "267",
    "281",
    "derailed",
    "derailment",
    "derail",
    "railcar",
    "railcars",
    "locomotive",
    "locomotives",
    "catenary",
    "interlocking",
]
