from core.config.variables import (
    LIST_REGIONS,
    LIST_LAWS,
    LIST_INC_TYPE_RAIL,
    LIST_DMG_EQUIP_RAIL,
    LIST_ARREST_REASON,
    LIST_COLL_WITH_RAIL,
    LIST_PARTISANS_GRP,
)

LIST_EXP_LAWS = [
    "Article 167 of the Criminal Code",
    "article 167 of the Criminal Code",
    "167 of the Criminal Code",
    "Article 167",
    "article 281",
    "167.",
    #
    "Article 205.1 of the Criminal Code",
    "article 205.1 of the Criminal Code",
    "205.1 of the Criminal Code",
    "Article 205.1",
    "article 205.1",
    "205.1",
    #
    "Article 205.2 of the Criminal Code",
    "article 205.2 of the Criminal Code",
    "205.2 of the Criminal Code",
    "Article 205.2",
    "article 205.2",
    "205.2",
    #
    "Article 205.3 of the Criminal Code",
    "article 205.3 of the Criminal Code",
    "205.3 of the Criminal Code",
    "Article 205.3",
    "article 205.3",
    "205.3",
    #
    "Article 207 of the Criminal Code",
    "article 207 of the Criminal Code",
    "207 of the Criminal Code",
    "Article 207",
    "article 207",
    "207.",
    #
    "Article 205 of the Criminal Code",
    "article 205 of the Criminal Code",
    "205 of the Criminal Code",
    "Article 205",
    "article 205",
    "205.",
    #
    "Article 275 of the Criminal Code",
    "article 275 of the Criminal Code",
    "275 of the Criminal Code",
    "Article 275",
    "article 275",
    "275.",
    #
    "Article 208 of the Criminal Code",
    "article 208 of the Criminal Code",
    "208 of the Criminal Code",
    "Article 208",
    "article 208",
    "208.",
    #
    "Article 281 of the Criminal Code",
    "article 281 of the Criminal Code",
    "281 of the Criminal Code",
    "Article 281",
    "article 281",
    "281.",
    #
]


DICT_REF_INPUT_RAILWAY = [
    {
        "name": "IDX",
        "label": "IDX",
        "type": "text_input",
        "value": "IDX",
        "st_col": "col1",
    },
    {
        "name": "filter_inc_railway",
        "label": "Filter Railway",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "add_final_inc_railway",
        "label": "Add Final Data Railway",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "filter_inc_arrest",
        "label": "Filter Arrest",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "add_final_inc_arrest",
        "label": "Add Final Data Arrest",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "filter_inc_sabotage",
        "label": "Filter Sabotage",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "add_final_inc_sabotage",
        "label": "Add Final Data Sabotage",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    #
    #
    {
        "name": "qualif_date_inc",
        "label": "Select Incident Date",
        "type": "date_input",
        "value": None,
        "st_col": "col3",
    },
    {
        "name": "qualif_region",
        "label": "Select Region",
        "type": "selectbox",
        "value": "",
        "options": LIST_REGIONS,
        "st_col": "col3",
    },
    {
        "name": "qualif_location",
        "label": "Location",
        "type": "text_input",
        "value": "",
        "st_col": "col3",
    },
    {
        "name": "qualif_inc_type",
        "label": "Select Incident Type",
        "type": "selectbox",
        "value": "",
        "options": LIST_INC_TYPE_RAIL,
        "st_col": "col3",
    },
    {
        "name": "qualif_dmg_eqp",
        "label": "Damage Equipment",
        "type": "selectbox",
        "value": "",
        "options": LIST_DMG_EQUIP_RAIL,
        "st_col": "col3",
    },
    {
        "name": "qualif_coll_with",
        "label": "Coll With",
        "type": "selectbox",
        "value": "",
        "options": LIST_COLL_WITH_RAIL,
        "st_col": "col3",
    },
    {
        "name": "qualif_nb_loco_dmg",
        "label": "Nb Locomotive Damage",
        "type": "number_input",
        "value": None,
        "st_col": "col3",
    },
    {
        "name": "qualif_nb_relay_dmg",
        "label": "Nb Relay Damage",
        "type": "number_input",
        "value": None,
        "st_col": "col3",
    },
    {
        "name": "qualif_gps",
        "label": "GPS",
        "type": "text_input",
        "value": "",
        "st_col": "col4",
    },
    {
        "name": "qualif_prtsn_arr",
        "label": "Prtsn Arr",
        "type": "toggle",
        "value": False,
        "st_col": "col4",
    },
    {
        "name": "qualif_prtsn_grp",
        "label": "Prtsn Group",
        "type": "selectbox",
        "value": "",
        "options": LIST_PARTISANS_GRP,
        "st_col": "col4",
    },
    {
        "name": "qualif_prtsn_names",
        "label": "Prtsn Names",
        "type": "text_input",
        "value": "",
        "st_col": "col4",
    },
    {
        "name": "qualif_prtsn_age",
        "label": "Prtsn Age",
        "type": "text_input",
        "value": "",
        "st_col": "col4",
    },
    {
        "name": "qualif_app_laws",
        "label": "Select Applied Laws",
        "type": "multiselect",
        "value": [],
        "options": LIST_LAWS,
        "st_col": "col4",
    },
    {
        "name": "qualif_comments",
        "label": "Comments",
        "type": "text_input",
        "value": "",
        "st_col": "col4",
    },
    {
        "name": "qualif_arrest_date",
        "label": "Select Arrest Date",
        "type": "date_input",
        "value": None,
        "st_col": "col3",
    },
    {
        "name": "qualif_arrest_reason",
        "label": "Select Reason Arrest",
        "type": "selectbox",
        "value": "",
        "options": LIST_ARREST_REASON,
        "st_col": "col3",
    },
    {
        "name": "qualif_person_name",
        "label": "Person Name",
        "type": "text_input",
        "value": "",
        "st_col": "col3",
    },
    {
        "name": "qualif_person_age",
        "label": "Person Age",
        "type": "number_input",
        "value": None,
        "st_col": "col3",
    },
    {
        "name": "qualif_sentence_date",
        "label": "Select Date Sentence",
        "type": "date_input",
        "value": None,
        "st_col": "col4",
    },
    {
        "name": "qualif_sentence_years",
        "label": "Sentence Years",
        "type": "number_input",
        "value": None,
        "st_col": "col4",
    },
]

DICT_REF_INPUT_ARREST = [
    {
        "name": "IDX",
        "label": "IDX",
        "type": "text_input",
        "value": "IDX",
        "st_col": "col1",
    },
    #
    ## Filter
    {
        "name": "filter_inc_railway",
        "label": "Filter Railway",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "add_final_inc_railway",
        "label": "Add Final Data Railway",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "filter_inc_arrest",
        "label": "Filter Arrest",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "add_final_inc_arrest",
        "label": "Add Final Data Arrest",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "filter_inc_sabotage",
        "label": "Filter Sabotage",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "add_final_inc_sabotage",
        "label": "Add Final Data Sabotage",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    #
    ## Qualif
    {
        "name": "qualif_arrest_date",
        "label": "Select Arrest Date",
        "type": "date_input",
        "value": None,
        "st_col": "col3",
    },
    {
        "name": "qualif_region",
        "label": "Select Region",
        "type": "selectbox",
        "value": "",
        "options": LIST_REGIONS,
        "st_col": "col3",
    },
    {
        "name": "qualif_location",
        "label": "Location",
        "type": "text_input",
        "value": "",
        "st_col": "col4",
    },
    # {
    #     "name": "qualif_arrest_reason",
    #     "label": "Select Reason Arrest",
    #     "type": "selectbox",
    #     "value": "",
    #     "options": [],
    #     "st_col": "col3",
    # },
    {
        "name": "qualif_arrest_reason",
        "label": "Select Reason Arrest",
        "type": "text_input",
        "value": "",
        "st_col": "col3",
    },
    {
        "name": "qualif_app_laws",
        "label": "Select Applied Laws",
        "type": "multiselect",
        "value": [],
        "options": LIST_LAWS,
        "st_col": "col3",
    },
    {
        "name": "qualif_sentence_date",
        "label": "Select Date Sentence",
        "type": "date_input",
        "value": None,
        "st_col": "col4",
    },
    {
        "name": "qualif_sentence_years",
        "label": "Sentence Years",
        "type": "number_input",
        "value": None,
        "st_col": "col4",
    },
    {
        "name": "qualif_person_name",
        "label": "Person Name",
        "type": "text_input",
        "value": "",
        "st_col": "col3",
    },
    {
        "name": "qualif_person_age",
        "label": "Person Age",
        "type": "number_input",
        "value": "",
        "st_col": "col4",
    },
    {
        "name": "qualif_person_job",
        "label": "Person Job",
        "type": "text_input",
        "value": "",
        "st_col": "col4",
    },
    {
        "name": "qualif_media_post",
        "label": "Media Post",
        "type": "text_input",
        "value": "",
        "st_col": "col4",
    },
    {
        "name": "qualif_comments",
        "label": "Comments",
        "type": "text_input",
        "value": "",
        "st_col": "col4",
    },
]


#
#
#
DICT_REF_INPUT_CLASS = [
    {
        "name": "IDX",
        "label": "IDX",
        "type": "text_input",
        "value": "IDX",
        "st_col": "col1",
    },
    {
        "name": "filter_inc_railway",
        "label": "Filter Railway",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "add_final_inc_railway",
        "label": "Add Final Data Railway",
        "type": "toggle",
        "value": True,
        "st_col": "col2",
    },
    {
        "name": "filter_inc_arrest",
        "label": "Filter Arrest",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "add_final_inc_arrest",
        "label": "Add Final Data Arrest",
        "type": "toggle",
        "value": True,
        "st_col": "col2",
    },
    {
        "name": "filter_inc_sabotage",
        "label": "Filter Sabotage",
        "type": "toggle",
        "value": True,
        "st_col": "col1",
    },
    {
        "name": "add_final_inc_sabotage",
        "label": "Add Final Data Sabotage",
        "type": "toggle",
        "value": True,
        "st_col": "col2",
    },
    #
    #
    {
        "name": "class_date_inc",
        "label": "Select Incident Date",
        "type": "date_input",
        "value": None,
        "st_col": "col2",
    },
    {
        "name": "class_region",
        "label": "Select Region",
        "type": "selectbox",
        "value": "",
        "options": LIST_REGIONS,
        "st_col": "col3",
    },
    {
        "name": "class_location",
        "label": "Location",
        "type": "text_input",
        "value": "",
        "st_col": "col4",
    },
    {
        "name": "class_gps",
        "label": "GPS",
        "type": "text_input",
        "value": "",
        "st_col": "col1",
    },
    {
        "name": "class_inc_type",
        "label": "Select Incident Type",
        "type": "selectbox",
        "value": "",
        "options": LIST_INC_TYPE_RAIL,
        "st_col": "col2",
    },
    {
        "name": "class_dmg_eqp",
        "label": "Damage Equipment",
        "type": "selectbox",
        "value": "",
        "options": LIST_DMG_EQUIP_RAIL,
        "st_col": "col3",
    },
    {
        "name": "class_coll_with",
        "label": "Coll With",
        "type": "selectbox",
        "value": "",
        "options": LIST_COLL_WITH_RAIL,
        "st_col": "col4",
    },
    {
        "name": "class_nb_loco_dmg",
        "label": "Nb Locomotive Damage",
        "type": "number_input",
        "value": None,
        "st_col": "col1",
    },
    {
        "name": "class_nb_relay_dmg",
        "label": "Nb Relay Damage",
        "type": "number_input",
        "value": None,
        "st_col": "col2",
    },
    {
        "name": "class_prtsn_grp",
        "label": "Prtsn Group",
        "type": "text_input",
        "value": "",
        "st_col": "col3",
    },
    {
        "name": "class_prtsn_arr",
        "label": "Prtsn Arr",
        "type": "toggle",
        "value": False,
        "st_col": "col4",
    },
    {
        "name": "class_prtsn_age",
        "label": "Prtsn Age",
        "type": "text_input",
        "value": "",
        "st_col": "col1",
    },
    {
        "name": "class_prtsn_names",
        "label": "Prtsn Names",
        "type": "text_input",
        "value": "",
        "st_col": "col2",
    },
    {
        "name": "class_app_laws",
        "label": "Select Applied Laws",
        "type": "multiselect",
        "value": [],
        "options": LIST_LAWS,
        "st_col": "col3",
    },
    {
        "name": "class_arrest_date",
        "label": "Select Arrest Date",
        "type": "date_input",
        "value": None,
        "st_col": "col4",
    },
    {
        "name": "class_arrest_reason",
        "label": "Select Reason Arrest",
        "type": "selectbox",
        "value": "",
        "options": LIST_ARREST_REASON,
        "st_col": "col1",
    },
    {
        "name": "class_person_name",
        "label": "Person Name",
        "type": "text_input",
        "value": "",
        "st_col": "col2",
    },
    {
        "name": "class_person_age",
        "label": "Person Age",
        "type": "number_input",
        "value": None,
        "st_col": "col3",
    },
    {
        "name": "class_sentence_date",
        "label": "Select Date Sentence",
        "type": "date_input",
        "value": None,
        "st_col": "col4",
    },
    {
        "name": "class_sentence_years",
        "label": "Sentence Years",
        "type": "number_input",
        "value": None,
        "st_col": "col1",
    },
    {
        "name": "class_comments",
        "label": "Comments",
        "type": "text_input",
        "value": "",
        "st_col": "col4",
    },
]
